#!/usr/bin/env python3
"""
Generate API Documentation from FastAPI OpenAPI specs
Fetches OpenAPI specs from running services and converts them to markdown
"""

import json
import requests
from datetime import datetime
from pathlib import Path


class Colors:
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    RED = '\033[0;31m'
    CYAN = '\033[0;36m'
    NC = '\033[0m'


def print_colored(message, color=Colors.NC):
    """Print colored message to terminal"""
    print(f"{color}{message}{Colors.NC}")


def check_service(url, name):
    """Check if a service is running"""
    try:
        response = requests.get(f"{url}", timeout=5)
        if response.status_code == 200:
            print_colored(f"OK: {name} is running", Colors.GREEN)
            return True
    except requests.exceptions.RequestException:
        pass
    
    print_colored(f"ERROR: {name} is not running", Colors.RED)
    print_colored(f"URL: {url}/health", Colors.YELLOW)
    print_colored("Please start it: docker-compose up -d", Colors.YELLOW)
    return False


def fetch_openapi_spec(url, output_path):
    """Fetch OpenAPI spec from service"""
    try:
        response = requests.get(f"{url}/openapi.json", timeout=5)
        response.raise_for_status()
        spec = response.json()
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(spec, f, indent=2)
        
        return spec
    except requests.exceptions.RequestException as e:
        print_colored(f"ERROR: Failed to fetch OpenAPI spec: {e}", Colors.RED)
        return None


def generate_basic_markdown(spec, service_name, base_url):
    """Generate basic markdown from OpenAPI spec"""
    md = []
    
    # Header
    md.append(f"# {spec['info']['title']}")
    md.append("")
    md.append(f"**Version**: {spec['info']['version']}")
    md.append(f"**Description**: {spec['info'].get('description', 'No description')}")
    md.append("")
    md.append("## Base URL")
    md.append("```")
    md.append(base_url)
    md.append("```")
    md.append("")
    
    # Endpoints
    md.append("## Endpoints")
    md.append("")
    
    for path, methods in spec.get('paths', {}).items():
        md.append(f"### `{path}`")
        md.append("")
      
        for method, operation in methods.items():
            if method.startswith('x-'):
                continue
            
            md.append(f"**{method.upper()}** {operation.get('summary', '')}")
            md.append("")
        
            if operation.get('description'):
                md.append(operation['description'])
                md.append("")
    
            # Parameters
            if operation.get('parameters'):
                md.append("**Parameters:**")
                md.append("")
                for param in operation['parameters']:
                    required = " (required)" if param.get('required') else ""
                    md.append(f"- `{param['name']}` ({param.get('in', 'query')}){required}: {param.get('description', 'No description')}")
                    md.append("")
       
            # Responses
            if operation.get('responses'):
                md.append("**Responses:**")
                md.append("")
                for status, response in operation['responses'].items():
                    md.append(f"- `{status}`: {response.get('description', 'No description')}")
                    md.append("")
            
        md.append("---")
        md.append("")
    
    return '\n'.join(md)


def create_index(output_dir):
    """Create API documentation index"""
    content = f"""# API Documentation

Auto-generated API documentation for all microservices.

## Services

### Customer Service
- [Customer Service API Documentation](customer-service.md)
- [OpenAPI Spec (JSON)](customer-service-openapi.json)
- Interactive Docs: http://localhost:8001/docs
- ReDoc: http://localhost:8001/redoc

### Product Service
- [Product Service API Documentation](product-service.md)
- [OpenAPI Spec (JSON)](product-service-openapi.json)
- Interactive Docs: http://localhost:8002/docs
- ReDoc: http://localhost:8002/redoc

## Authentication

All endpoints require JWT authentication. See [Security Guide](../security/security-guide.md) for details.

### Getting a Token

```bash
curl -X POST http://localhost:8180/realms/api-gateway-poc/protocol/openid-connect/token \\
  -d "client_id=test-client" \\
  -d "username=testuser" \\
  -d "password=testpass" \\
  -d "grant_type=password"
```

### Using a Token

```bash
curl -H "Authorization: Bearer <TOKEN>" http://localhost:8080/customers
```

---

**Last Updated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Generated by**: generate-api-docs.py

"""
    
    index_path = output_dir / "README.md"
    with open(index_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print_colored("OK: API documentation index created", Colors.GREEN)


def main():
    """Main function"""
    print_colored("=== API Documentation Generator ===", Colors.GREEN)
    print()
    
    # Configuration
    services = {
        'customer-service': {
            'url': 'http://localhost:8001',
            'health': '/customers/health'
        },
        'product-service': {
            'url': 'http://localhost:8002',
            'health': '/products/health'
        }
    }
    
    output_dir = Path('docs/api')
    
    # Check if services are running
    print_colored("Checking if services are running...", Colors.YELLOW)
    for name, config in services.items():
        health_url = config['url'] + config['health']
        if not check_service(health_url, name):
            return 1
    
    # Create output directory
    print()
    print_colored("Creating output directory...", Colors.YELLOW)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Fetch OpenAPI specs and generate markdown
    print()
    print_colored("Fetching OpenAPI specifications...", Colors.YELLOW)
    
    for name, config in services.items():
        # Fetch spec
        spec_path = output_dir / f"{name}-openapi.json"
        spec = fetch_openapi_spec(config['url'], spec_path)
        
        if not spec:
            return 1
        
        print_colored(f"OK: {name} OpenAPI spec saved", Colors.GREEN)
        
        # Generate markdown
        md_path = output_dir / f"{name}.md"
        markdown = generate_basic_markdown(spec, name, config['url'])
        
        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(markdown)
        
        print_colored(f"OK: {name} markdown generated", Colors.GREEN)
    
    # Create index
    print()
    print_colored("Creating documentation index...", Colors.YELLOW)
    create_index(output_dir)
    
    # Summary
    print()
    print_colored("=== Documentation Generated Successfully ===", Colors.GREEN)
    print()
    print_colored("Generated files:", Colors.YELLOW)
    print(f"  - {output_dir}/README.md")
    print(f"  - {output_dir}/customer-service.md")
    print(f"  - {output_dir}/customer-service-openapi.json")
    print(f"  - {output_dir}/product-service.md")
    print(f"  - {output_dir}/product-service-openapi.json")
    print()
    print_colored("View documentation: cat docs/api/README.md", Colors.CYAN)
    print()
    
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
